### PR TITLE
Updated project to remove 64-bit related issues (CGFloat <-> float)

### PR DESCRIPTION
**Pull request by tbrannam**
Updated code to remove warnings related to CGFloat being 64-bit on newer platforms.
Added Cocoapod podspec - (would required a tag in upsteam fork)
Added patch from @bwake2012 targetContentOffsetForProposedContentOffset adjusts scroll position to keep images centered on selectedIndexPath when the bounds change (i.e. rotation)

### CODE REVIEW

**Comment by tbrannam** [comment]
oh the irony -  http://toxicsoftware.com/issuerequests.html

**Comment by schwa** [comment]
Burrrrrn.

**Comment by schwa** [comment]
Humble pie eating aside. I have a lot of projects on Github that are really twilighted now. I could either:

* Delete 'em if I don't want to maintain them…
* Prevent pull requests
* Spend a portion of my time going through pull requests on projects I have no interest in maintaining
* Ignore 'em and let other people provide more active forks.

For this project I've gone for option 4. Putting a project on github doesn't commit me to a lifetime of supporting it. It's github: make your own fork and maintain that.

**Comment by tbrannam** [comment]
Understood.  Just came across the blog post and remebered my PR.   All kidding asiide I appreciate your work.

**Pull request merged**
